### ISSUE TITLE
Build errors on Linux Mint 18.3 with Allegro 4.4

### ISSUE THREAD

**Issue by mrgw454** [ilmenit/RastaConverter#3]
I recently downloaded the source and tried to build RastaConverter on a Linux Mint 18.3 64bit workstation.  I received the following errors:

...

rasta.cpp: In member function ‘void RastaConverter::LoadOnOffFile(const char*)’:
rasta.cpp:664:65: error: no matching function for call to ‘transform(std::__cxx11::basic_string<char>::iterator, std::__cxx11::basic_string<char>::iterator, std::__cxx11::basic_string<char>::iterator, <unresolved overloaded function type>)’
   std::transform(line.begin(), line.end(), line.begin(), toupper);
                                                                 ^
...
...

rasta.cpp:1536:3: error: ‘__timeb64’ was not declared in this scope
   __timeb64 t;
   ^
rasta.cpp:1537:11: error: ‘t’ was not declared in this scope
   _ftime(&t);
           ^
rasta.cpp:1537:12: error: ‘_ftime’ was not declared in this scope
   _ftime(&t);
            ^

...

d7577 ~/source/RastaConverter/src $ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

d7577 ~/source/RastaConverter/src $ cc --version
cc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Any help you can provide would be appreciated.

Thanks!

**Comment by polluks** [comment]
Indeed, this code is a non-portable Microsoft extension.

**Comment by ilmenit** [comment]
Resolved in Beta9 by removal of dependency on Allegro library.

**Comment by ilmenit** [comment]
Resolved in Beta9
